###
POST https://{{host}}/api/{{api_version_prefix}}/{{api_key_client}}/admin/contacts
Accept: */*
Cache-Control: no-cache
Content-Type: application/json; charset=utf-8
X-LOYALTY-API-KEY-ADMIN: {{api_key_role_admin}}
Idempotency-Key: 123456-85d2-4e47-b568-4faa746e2213

{
  "full_name": {
    "name": "Иван1",
    "surname": "Иванов1",
    "patronymic": "Иванович1"
  },
  "timezone_utc_offset": null,
  "gender": "male",
  "birthday": null,
  "external_ids": []
}

###
GET https://{{host}}/api/{{api_version_prefix}}/{{api_key_client}}/admin/contacts/74957029-e3b8-4419-8557-38a42140cc6d
Accept: */*
Cache-Control: no-cache
Content-Type: application/json; charset=utf-8
X-LOYALTY-API-KEY-ADMIN: {{api_key_role_admin}}