###
# WTF 404??????
# GET https://{{host}}/api/{{api_version_prefix}}/{{api_key_client}}/admin/contacts/a2da94f5-fa82-4f8e-973a-8aa8d15207f8
GET https://{{host}}/api/{{api_version_prefix}}/{{api_key_client}}/admin/contacts/dc088068-9904-4272-b0a8-985a109582e1
Accept: */*
Cache-Control: no-cache
Content-Type: application/json; charset=utf-8
X-LOYALTY-API-KEY-ADMIN: {{api_key_role_admin}}