### добавление операци на точке контакта в привязке к валидной карте
POST https://{{host}}/api/{{api_version_prefix}}/{{api_key_client}}/admin/1c/operations/refund
Accept: */*
Cache-Control: no-cache
Content-Type: application/json; charset=utf-8
X-LOYALTY-API-KEY-ADMIN: {{api_key_role_admin}}

{
    "loyalty": {
       "touch_point_id": "{{touch_point_id}}"
    },
    "operation_type": "refund",
    "payload":{
       "operation_id": "20210807.2302",
        "money_sum": {
            "amount": "10.00",
            "currency": "RUB"
        },
        "bonus_sum": {
            "amount": "0.00",
            "currency": "RUB"
        }
    }
}

