###
GET https://{{host}}/api/{{api_version_prefix}}/{{api_key_client}}/admin/application-journal?page=10
Accept: */*
Cache-Control: no-cache
Content-Type: application/json; charset=utf-8
X-LOYALTY-API-KEY-ADMIN: {{api_key_role_admin}}
